Repository MrKrishnaAgarwal/Swags-for-Developers, pull requests merged in 2022-10, with the labels that each got.

#11 Add COMMUNITY CLASSROOM BLOGGING CHALLENGES
  Swags.md
Labels: good first issue, hacktoberfest

#16 Added CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added Kong website to swags.md
  Swags.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 Added JS Bin for swags.
  Swags.md
Labels: hacktoberfest-accepted

#33 Added JinaAI Swag
  Swags.md
Labels: hacktoberfest-accepted

#34 Added Gatsby Swag
  Swags.md
Labels: hacktoberfest-accepted

#39 Added contributors image in readme
  README.md
Labels: hacktoberfest-accepted

#41 Added codedam swag info
  README.md
Labels: hacktoberfest-accepted

#42 feat: Added more swag opportunities 💡
  README.md
Labels: documentation, enhancement

#43 fixed Codedamn spelling
  README.md
Labels: invalid
