Repository MrKrishnaAgarwal/Swags-for-Developers, pull requests merged in 2023-10, with the labels that each got.

#48 The Gita Initiative Website is down
  README.md
Labels: documentation, hacktoberfest

#53 takeout: swag info expired
  README.md
Labels: bug, documentation, hacktoberfest, hacktoberfest-accepted

#52 add: RedwoodJS swag info (updated)
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted
